/**
 * Campos de texto editables por sección (builder preview).
 * Solo strings simples en v1; arrays complejos quedan fuera.
 * Recetas Beat (pasos dx/dy) aún no son un campo: el motion vive en JSX/presets.
 * Ver docs/scrolllab-beat.md.
 */
export const SECTION_FIELDS = {
  'chapters/NavMinimal': [
    { key: 'brand', label: 'Brand', type: 'text' },
    {
      key: 'linksText',
      label: 'Links (uno por línea, "Texto | #ancla")',
      type: 'textarea',
    },
  ],
  'chapters/HeroKinetic': [
    { key: 'lineOne', label: 'Linea 1', type: 'text' },
    { key: 'lineTwo', label: 'Linea 2', type: 'text' },
    { key: 'lineThree', label: 'Linea 3', type: 'text' },
    { key: 'kicker', label: 'Kicker', type: 'text' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
  ],
  'chapters/ManifestoReveal': [
    { key: 'chapter', label: 'Chapter', type: 'text' },
    { key: 'total', label: 'Total', type: 'text' },
    { key: 'label', label: 'Label', type: 'text' },
  ],
  'chapters/QuoteBreak': [
    { key: 'chapter', label: 'Chapter', type: 'text' },
    { key: 'total', label: 'Total', type: 'text' },
    { key: 'label', label: 'Label', type: 'text' },
    { key: 'quote', label: 'Quote', type: 'textarea' },
    { key: 'attribution', label: 'Attribution', type: 'text' },
  ],
  'chapters/FooterCTA': [
    { key: 'ctaWord', label: 'CTA', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
  ],
  'nocturne/NavNocturne': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'marker', label: 'Marker', type: 'text' },
    {
      key: 'linksText',
      label: 'Links (uno por línea, "Texto | #ancla")',
      type: 'textarea',
    },
  ],
  'nocturne/HeroCinematic': [
    { key: 'titleTop', label: 'Title top', type: 'text' },
    { key: 'titleBottom', label: 'Title bottom', type: 'text' },
    { key: 'kicker', label: 'Kicker', type: 'text' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
  ],
  'nocturne/OutroCTA': [
    { key: 'ctaWord', label: 'CTA', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
  ],
  'monolith/NavBrutal': [
    { key: 'brand', label: 'Brand', type: 'text' },
    {
      key: 'linksText',
      label: 'Links (uno por línea, "Texto | #ancla")',
      type: 'textarea',
    },
  ],
  'monolith/HeroThree': [
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
    {
      key: 'shape',
      label: '3D shape',
      type: 'select',
      options: [
        { value: 'icosahedron', label: 'Icosahedron' },
        { value: 'box', label: 'Box' },
        { value: 'octahedron', label: 'Octahedron' },
        { value: 'torus', label: 'Torus' },
        { value: 'sphere', label: 'Sphere' },
      ],
    },
    { key: 'modelUrl', label: 'Modelo 3D propio (.glb)', type: 'model' },
  ],
  'monolith/FooterBrutal': [
    { key: 'ctaWord', label: 'CTA', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
  ],
  'fizz/NavFizz': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'shopLabel', label: 'Dropdown 1 — label', type: 'text' },
    {
      key: 'shopItems',
      label: 'Dropdown 1 — ítems (uno por línea)',
      type: 'textarea',
    },
    { key: 'learnLabel', label: 'Dropdown 2 — label', type: 'text' },
    {
      key: 'learnItems',
      label: 'Dropdown 2 — ítems (uno por línea)',
      type: 'textarea',
    },
    { key: 'linkLabel', label: 'Link simple', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
  ],
  'fizz/HeroBubbles': [
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'tagline', label: 'Tagline', type: 'textarea' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
    {
      key: 'flavor',
      label: 'Flavor (can + backdrop)',
      type: 'select',
      options: [
        { value: 'berry', label: 'Berry (pink)' },
        { value: 'citrus', label: 'Citrus (orange)' },
        { value: 'tropical', label: 'Tropical (coral)' },
        { value: 'mint', label: 'Mint (green)' },
      ],
    },
    { key: 'canImage', label: 'Lata PNG (override)', type: 'image' },
    { key: 'canLabel', label: 'Texto lata (legacy)', type: 'text' },
    { key: 'modelUrl', label: 'Modelo 3D propio (.glb)', type: 'model' },
  ],
  'fizz/FlavorWorlds': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
  ],
  'fizz/BubbleBenefits': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
  ],
  'fizz/CanCarousel': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
    { key: 'canLabel', label: 'Texto en latas (fallback SVG)', type: 'text' },
    { key: 'can1Name', label: 'Lata 1 — nombre', type: 'text' },
    { key: 'can1Note', label: 'Lata 1 — nota', type: 'text' },
    { key: 'can1Image', label: 'Lata 1 — PNG (override)', type: 'image' },
    { key: 'can2Name', label: 'Lata 2 — nombre', type: 'text' },
    { key: 'can2Note', label: 'Lata 2 — nota', type: 'text' },
    { key: 'can2Image', label: 'Lata 2 — PNG (override)', type: 'image' },
    { key: 'can3Name', label: 'Lata 3 — nombre', type: 'text' },
    { key: 'can3Note', label: 'Lata 3 — nota', type: 'text' },
    { key: 'can3Image', label: 'Lata 3 — PNG (override)', type: 'image' },
    { key: 'can4Name', label: 'Lata 4 — nombre', type: 'text' },
    { key: 'can4Note', label: 'Lata 4 — nota', type: 'text' },
    { key: 'can4Image', label: 'Lata 4 — PNG (override)', type: 'image' },
    { key: 'can5Name', label: 'Lata 5 — nombre', type: 'text' },
    { key: 'can5Note', label: 'Lata 5 — nota', type: 'text' },
    { key: 'can5Image', label: 'Lata 5 — PNG (override)', type: 'image' },
  ],
  'fizz/PopManifesto': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'text', label: 'Text', type: 'textarea' },
  ],
  'fizz/FooterSplash': [
    { key: 'ctaWord', label: 'CTA', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
  ],
  'velocity/NavVelocity': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
    {
      key: 'linksText',
      label: 'Links (uno por línea, "Texto | #ancla")',
      type: 'textarea',
    },
  ],
  'velocity/HeroStrike': [
    { key: 'lineLeft', label: 'Line left', type: 'text' },
    { key: 'lineLeft2', label: 'Line left 2', type: 'text' },
    { key: 'lineRight', label: 'Line right', type: 'text' },
    { key: 'lineRight2', label: 'Line right 2', type: 'text' },
    { key: 'caption', label: 'Caption', type: 'text' },
    { key: 'imgBack', label: 'Layer back (URL)', type: 'text' },
    { key: 'imgMid', label: 'Layer mid (URL)', type: 'text' },
    { key: 'imgFront', label: 'Layer front (URL)', type: 'text' },
  ],
  'velocity/HelmetGrid': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
  ],
  'velocity/TrackMerge': [
    { key: 'pathLabelA', label: 'Path label A', type: 'text' },
    { key: 'pathLabelB', label: 'Path label B', type: 'text' },
    { key: 'mergeTitleA', label: 'Merge title A', type: 'text' },
    { key: 'mergeTitleB', label: 'Merge title B', type: 'text' },
    { key: 'mergeAccent', label: 'Merge accent', type: 'text' },
  ],
  'velocity/ParallaxRise': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'cta', label: 'CTA', type: 'text' },
  ],
  'velocity/FooterVelocity': [
    { key: 'line', label: 'Line', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
  ],
  'atelier/NavAtelier': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
    { key: 'label', label: 'Label', type: 'text' },
    { key: 'menuLabel', label: 'Menu label', type: 'text' },
    {
      key: 'linksText',
      label: 'Links (uno por línea, "Texto | #ancla")',
      type: 'textarea',
    },
  ],
  'atelier/HeroMeaning': [
    { key: 'line1', label: 'Line 1', type: 'text' },
    { key: 'line2', label: 'Line 2', type: 'text' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
  ],
  'atelier/AboutClarity': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'textarea' },
    { key: 'body', label: 'Body', type: 'textarea' },
  ],
  'atelier/ServicesStone': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'service1Title', label: 'Service 1 — title', type: 'text' },
    { key: 'service1Body', label: 'Service 1 — body', type: 'textarea' },
    { key: 'service2Title', label: 'Service 2 — title', type: 'text' },
    { key: 'service2Body', label: 'Service 2 — body', type: 'textarea' },
    { key: 'service3Title', label: 'Service 3 — title', type: 'text' },
    { key: 'service3Body', label: 'Service 3 — body', type: 'textarea' },
    { key: 'service4Title', label: 'Service 4 — title', type: 'text' },
    { key: 'service4Body', label: 'Service 4 — body', type: 'textarea' },
  ],
  'atelier/VisionShutter': [
    { key: 'line1', label: 'Line 1', type: 'text' },
    { key: 'line2', label: 'Line 2', type: 'text' },
    { key: 'word1', label: 'Word 1', type: 'text' },
    { key: 'word2', label: 'Word 2', type: 'text' },
    { key: 'word3', label: 'Word 3', type: 'text' },
  ],
  'atelier/SelectedWork': [
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
  ],
  'atelier/KeyFacts': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
  ],
  'atelier/WordStripe': [
    { key: 'line1', label: 'Line 1', type: 'text' },
    { key: 'line2', label: 'Line 2', type: 'text' },
    { key: 'word1', label: 'Word 1', type: 'text' },
    { key: 'word2', label: 'Word 2', type: 'text' },
    { key: 'word3', label: 'Word 3', type: 'text' },
  ],
  'atelier/StudioCards': [
    { key: 'note', label: 'Note', type: 'textarea' },
    { key: 'cta', label: 'CTA', type: 'text' },
  ],
  'atelier/FooterAtelier': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'line', label: 'Headline', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
    { key: 'brand', label: 'Brand mark', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
    { key: 'email', label: 'Email', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
  ],
  'unity/NavUnity': [
    { key: 'brand', label: 'Brand / phrase', type: 'text' },
    { key: 'logo', label: 'Logo text', type: 'text' },
    { key: 'logoSrc', label: 'Logo image', type: 'image' },
    { key: 'linksText', label: 'Links (3)', type: 'textarea' },
    { key: 'menuLabel', label: 'Menu label', type: 'text' },
  ],
  'unity/HeroTwin': [
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'headline', label: 'Headline', type: 'textarea' },
  ],
  'unity/MosaicSlider': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'textarea' },
    { key: 'img1', label: 'Image 1', type: 'image' },
    { key: 'img2', label: 'Image 2', type: 'image' },
    { key: 'img3', label: 'Image 3', type: 'image' },
    { key: 'img4', label: 'Image 4', type: 'image' },
    { key: 'img5', label: 'Image 5', type: 'image' },
    { key: 'img6', label: 'Image 6', type: 'image' },
    { key: 'img7', label: 'Image 7', type: 'image' },
    { key: 'img8', label: 'Image 8', type: 'image' },
  ],
  'unity/UniversalLang': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'number', label: 'Number', type: 'text' },
    { key: 'numberLabel', label: 'Number label', type: 'text' },
  ],
  'unity/LanguageBlock': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'line1', label: 'Line 1', type: 'text' },
    { key: 'line2', label: 'Line 2', type: 'text' },
    { key: 'line3', label: 'Line 3', type: 'text' },
    { key: 'note', label: 'Note', type: 'text' },
    { key: 'bg', label: 'Background', type: 'text' },
    { key: 'fg', label: 'Foreground', type: 'text' },
    { key: 'img1', label: 'Image 1', type: 'image' },
    { key: 'img2', label: 'Image 2', type: 'image' },
    { key: 'img3', label: 'Image 3', type: 'image' },
    { key: 'anchor', label: 'Anchor id', type: 'text' },
  ],
  'unity/LastPortrait': [
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'name', label: 'Name', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'question', label: 'Question', type: 'text' },
    { key: 'caption', label: 'Caption', type: 'textarea' },
    { key: 'img', label: 'Portrait', type: 'image' },
    { key: 'stat1Label', label: 'Stat 1 label', type: 'text' },
    { key: 'stat1Value', label: 'Stat 1 value', type: 'text' },
    { key: 'stat2Label', label: 'Stat 2 label', type: 'text' },
    { key: 'stat2Value', label: 'Stat 2 value', type: 'text' },
    { key: 'stat3Label', label: 'Stat 3 label', type: 'text' },
    { key: 'stat3Value', label: 'Stat 3 value', type: 'text' },
  ],
  'unity/StageLines': [
    { key: 'eyebrow1', label: 'Eyebrow 1', type: 'text' },
    { key: 'line1', label: 'Line 1', type: 'text' },
    { key: 'img1', label: 'Image 1', type: 'image' },
    { key: 'eyebrow2', label: 'Eyebrow 2', type: 'text' },
    { key: 'line2', label: 'Line 2', type: 'text' },
    { key: 'img2', label: 'Image 2', type: 'image' },
  ],
  'unity/FooterTrophy': [
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'accentWord', label: 'Accent word', type: 'text' },
    { key: 'metaLeft', label: 'Meta left', type: 'text' },
    { key: 'metaRight', label: 'Meta right', type: 'text' },
    { key: 'orbSrc', label: 'Orb photo', type: 'image' },
  ],
  'ratio/NavRatio': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'linksText', label: 'Links (uno por línea)', type: 'textarea' },
    { key: 'ruptureLabel', label: 'Rupture label', type: 'text' },
    { key: 'onLabel', label: 'On', type: 'text' },
    { key: 'offLabel', label: 'Off', type: 'text' },
    { key: 'credit', label: 'Credit', type: 'text' },
    { key: 'menuLabel', label: 'Menu label', type: 'text' },
  ],
  'ratio/HeroTools': [
    { key: 'word1', label: 'Word 1 (4–5 letras)', type: 'text' },
    { key: 'word2', label: 'Word 2 (corta, una pieza)', type: 'text' },
    { key: 'word3', label: 'Word 3 (4 letras)', type: 'text' },
    { key: 'word4', label: 'Word 4 (4–6 letras, una pieza)', type: 'text' },
    { key: 'word5', label: 'Word 5 (8–12 letras)', type: 'text' },
    { key: 'note', label: 'Top note', type: 'textarea' },
    { key: 'aside', label: 'Aside', type: 'textarea' },
  ],
  'ratio/FourPlates': [
    { key: 'eyebrow', label: 'Title', type: 'text' },
    { key: 'plate1Title', label: 'Plate 1', type: 'text' },
    { key: 'plate2Title', label: 'Plate 2', type: 'text' },
    { key: 'plate3Title', label: 'Plate 3', type: 'text' },
    { key: 'plate4Title', label: 'Plate 4', type: 'text' },
  ],
  'ratio/SplitStudy': [
    { key: 'kicker', label: 'Kicker', type: 'text' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'index', label: 'Index', type: 'text' },
    { key: 'specLabel', label: 'Spec 1 label', type: 'text' },
    { key: 'specValue', label: 'Spec 1 value', type: 'text' },
    { key: 'spec2Label', label: 'Spec 2 label', type: 'text' },
    { key: 'spec2Value', label: 'Spec 2 value', type: 'text' },
    { key: 'spec3Label', label: 'Spec 3 label', type: 'text' },
    { key: 'spec3Value', label: 'Spec 3 value', type: 'text' },
    { key: 'spec4Label', label: 'Spec 4 label', type: 'text' },
    { key: 'spec4Value', label: 'Spec 4 value', type: 'text' },
    { key: 'quote', label: 'Quote', type: 'textarea' },
    { key: 'quoteBy', label: 'Quote name', type: 'text' },
    { key: 'quoteRole', label: 'Quote role', type: 'text' },
    { key: 'panel2Label', label: 'Panel 2 label', type: 'text' },
    { key: 'panel2Size', label: 'Panel 2 size', type: 'text' },
    { key: 'img', label: 'Panel 1 image', type: 'image' },
    { key: 'img2', label: 'Panel 2 image', type: 'image' },
    { key: 'anchor', label: 'Anchor id', type: 'text' },
  ],
  'ratio/FitStack': [
    { key: 'noteLabel', label: 'Notes label', type: 'text' },
    { key: 'note1', label: 'Note 1', type: 'text' },
    { key: 'note2', label: 'Note 2', type: 'text' },
    { key: 'note2Mark', label: 'Note 2 underline', type: 'text' },
    { key: 'note3', label: 'Note 3', type: 'text' },
    { key: 'note3Mark', label: 'Note 3 underline', type: 'text' },
    { key: 'phrase', label: 'Headline', type: 'text' },
    { key: 'breakLine', label: 'Title two', type: 'text' },
    { key: 'rulesLine', label: 'Title three', type: 'text' },
    { key: 'worthLine', label: 'Title four', type: 'text' },
    { key: 'closer', label: 'Closer line', type: 'text' },
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'studio', label: 'Studio', type: 'text' },
    { key: 'anchor', label: 'Anchor id', type: 'text' },
  ],
  'ratio/PlateStudy': [
    { key: 'index', label: 'Index', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'variant', label: 'Plate variant', type: 'text' },
    { key: 'specLabel', label: 'Spec 1 label', type: 'text' },
    { key: 'specValue', label: 'Spec 1 value', type: 'text' },
    { key: 'spec2Label', label: 'Spec 2 label', type: 'text' },
    { key: 'spec2Value', label: 'Spec 2 value', type: 'text' },
    { key: 'spec3Label', label: 'Spec 3 label', type: 'text' },
    { key: 'spec3Value', label: 'Spec 3 value', type: 'text' },
    { key: 'spec4Label', label: 'Spec 4 label', type: 'text' },
    { key: 'spec4Value', label: 'Spec 4 value', type: 'text' },
    { key: 'caseTitle', label: 'Case title', type: 'text' },
    { key: 'caseMeta', label: 'Case meta', type: 'text' },
    { key: 'img', label: 'Case image', type: 'image' },
    { key: 'img2', label: 'Case image 2', type: 'image' },
    { key: 'step1Label', label: 'Step 1 label', type: 'text' },
    { key: 'step1Body', label: 'Step 1 body', type: 'text' },
    { key: 'step2Label', label: 'Step 2 label', type: 'text' },
    { key: 'step2Body', label: 'Step 2 body', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
    { key: 'anchor', label: 'Anchor id', type: 'text' },
  ],
  'ratio/BreakRules': [
    { key: 'line1', label: 'Line 1', type: 'text' },
    { key: 'line2', label: 'Line 2', type: 'text' },
    { key: 'line3', label: 'Line 3', type: 'text' },
    { key: 'aside', label: 'Aside', type: 'text' },
    { key: 'anchor', label: 'Anchor id', type: 'text' },
  ],
  'ratio/FooterLedger': [
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'ghost', label: 'Ghost word', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'studio', label: 'Studio', type: 'text' },
    { key: 'row1Label', label: 'Row 1 label', type: 'text' },
    { key: 'row1Value', label: 'Row 1 value', type: 'text' },
    { key: 'row2Label', label: 'Row 2 label', type: 'text' },
    { key: 'row2Value', label: 'Row 2 value', type: 'text' },
    { key: 'row3Label', label: 'Row 3 label', type: 'text' },
    { key: 'row3Value', label: 'Row 3 value', type: 'text' },
    { key: 'row4Label', label: 'Row 4 label', type: 'text' },
    { key: 'row4Value', label: 'Row 4 value', type: 'text' },
    { key: 'spine1Title', label: 'Spine 1 title', type: 'text' },
    { key: 'spine1Author', label: 'Spine 1 author', type: 'text' },
    { key: 'spine2Title', label: 'Spine 2 title', type: 'text' },
    { key: 'spine2Author', label: 'Spine 2 author', type: 'text' },
    { key: 'spine3Title', label: 'Spine 3 title', type: 'text' },
    { key: 'spine3Author', label: 'Spine 3 author', type: 'text' },
    { key: 'spine4Title', label: 'Spine 4 title', type: 'text' },
    { key: 'spine4Author', label: 'Spine 4 author', type: 'text' },
    { key: 'spine5Title', label: 'Spine 5 title', type: 'text' },
    { key: 'spine5Author', label: 'Spine 5 author', type: 'text' },
  ],
  'vanta/NavVanta': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'linksText', label: 'Links (uno por línea)', type: 'textarea' },
    { key: 'playLabel', label: 'Play label', type: 'text' },
    { key: 'liveLabel', label: 'Live label', type: 'text' },
    { key: 'menuLabel', label: 'Menu label', type: 'text' },
    { key: 'discoverLabel', label: 'Discover label', type: 'text' },
    { key: 'drawerLinksText', label: 'Drawer links (uno por línea)', type: 'textarea' },
    { key: 'connectLabel', label: 'Connect label', type: 'text' },
    { key: 'socialText', label: 'Social (uno por línea)', type: 'textarea' },
    { key: 'buyLabel', label: 'Buy label', type: 'text' },
    { key: 'buyMarket', label: 'Buy market', type: 'text' },
    { key: 'closeLabel', label: 'Close label', type: 'text' },
    { key: 'langLabel', label: 'Lang', type: 'text' },
    { key: 'pageLabel', label: 'Page label', type: 'text' },
    { key: 'year', label: 'Year', type: 'text' },
  ],
  'vanta/BootVanta': [
    { key: 'brand', label: 'Brand', type: 'text' },
    { key: 'loadingLabel', label: 'Loading label', type: 'text' },
    { key: 'soundLabel', label: 'Sound label', type: 'text' },
    { key: 'readyLabel', label: 'Ready label', type: 'text' },
    { key: 'playLabel', label: 'Play label', type: 'text' },
  ],
  'vanta/HeroOperators': [
    { key: 'line', label: 'Manifesto', type: 'textarea' },
    { key: 'word1', label: 'Word 1', type: 'text' },
    { key: 'word2', label: 'Word 2', type: 'text' },
    { key: 'word3', label: 'Word 3', type: 'text' },
    { key: 'tag1', label: 'Tag 1', type: 'text' },
    { key: 'tag2', label: 'Tag 2', type: 'text' },
    { key: 'tag3', label: 'Tag 3', type: 'text' },
    { key: 'worldLine', label: 'World line', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
    { key: 'img', label: 'Hero image', type: 'image' },
    { key: 'img2', label: 'Card behind', type: 'image' },
  ],
  'vanta/KeeperVista': [
    { key: 'worldLine', label: 'World line', type: 'text' },
    { key: 'line', label: 'Line', type: 'text' },
    { key: 'power', label: 'Power line', type: 'textarea' },
    { key: 'index', label: 'Index', type: 'text' },
    { key: 'img', label: 'Plate wide', type: 'image' },
    { key: 'img2', label: 'Plate portrait', type: 'image' },
    { key: 'img3', label: 'Plate tall', type: 'image' },
    { key: 'img4', label: 'Vista painting', type: 'image' },
  ],
  'vanta/CollectionDesk': [
    { key: 'kicker', label: 'Kicker', type: 'text' },
    { key: 'mark', label: 'Mark', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'crystalLabel', label: 'Crystal label', type: 'text' },
    { key: 'eyeLabel', label: 'Eye label', type: 'text' },
    { key: 'img', label: 'Plate', type: 'image' },
    { key: 'img2', label: 'Crystal', type: 'image' },
    { key: 'img3', label: 'Eye', type: 'image' },
  ],
  'vanta/OperatorFan': [
    { key: 'kicker', label: 'Kicker', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'img', label: 'Card 1', type: 'image' },
    { key: 'img2', label: 'Card 2', type: 'image' },
    { key: 'img3', label: 'Card 3', type: 'image' },
    { key: 'img4', label: 'Card 4', type: 'image' },
    { key: 'img5', label: 'Swap 1', type: 'image' },
    { key: 'img6', label: 'Swap 2', type: 'image' },
    { key: 'img7', label: 'Swap 3', type: 'image' },
    { key: 'img8', label: 'Swap 4', type: 'image' },
  ],
  'vanta/CitadelStage': [
    { key: 'index', label: 'Index', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'holdHint', label: 'Hold hint', type: 'text' },
    { key: 'feedLabel', label: 'Feed label', type: 'text' },
    { key: 'img', label: 'Citadel', type: 'image' },
    { key: 'img2', label: 'Scan overlay', type: 'image' },
  ],
  'vanta/FactionHold': [
    { key: 'index', label: 'Index', type: 'text' },
    { key: 'kicker', label: 'Kicker', type: 'text' },
    { key: 'line', label: 'Line', type: 'text' },
    { key: 'leftName', label: 'Left name', type: 'text' },
    { key: 'leftBody', label: 'Left body', type: 'text' },
    { key: 'rightName', label: 'Right name', type: 'text' },
    { key: 'rightBody', label: 'Right body', type: 'text' },
    { key: 'holdHint', label: 'Hold hint', type: 'text' },
    { key: 'feedLabel', label: 'Feed label', type: 'text' },
    { key: 'img', label: 'Left image', type: 'image' },
    { key: 'img2', label: 'Right image', type: 'image' },
  ],
  'vanta/WorldVista': [
    { key: 'index', label: 'Index', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'img', label: 'Vista', type: 'image' },
    { key: 'img2', label: 'Tower', type: 'image' },
    { key: 'img3', label: 'Eye', type: 'image' },
    { key: 'img4', label: 'Portal', type: 'image' },
  ],
  'vanta/FooterDrop': [
    { key: 'mark', label: 'Mark', type: 'text' },
    { key: 'hint', label: 'Hint', type: 'text' },
    { key: 'cta', label: 'CTA', type: 'text' },
    { key: 'boot', label: 'Boot line', type: 'text' },
    { key: 'fileLine', label: 'File line', type: 'text' },
    { key: 'story', label: 'Story', type: 'text' },
    { key: 'journal', label: 'Journal', type: 'text' },
    { key: 'media', label: 'Media', type: 'text' },
    { key: 'gallery', label: 'Gallery', type: 'text' },
    { key: 'about', label: 'About', type: 'text' },
    { key: 'contact', label: 'Contact', type: 'text' },
    { key: 'legal', label: 'Legal', type: 'text' },
    { key: 'col1', label: 'Column 1', type: 'text' },
    { key: 'col2', label: 'Column 2', type: 'text' },
    { key: 'col3', label: 'Column 3', type: 'text' },
    { key: 'img', label: 'Cutout', type: 'image' },
    { key: 'img2', label: 'Sliver 1', type: 'image' },
    { key: 'img3', label: 'Sliver 2', type: 'image' },
    { key: 'img4', label: 'Sliver 3', type: 'image' },
  ],
  'contact/ContactForm': [
    {
      key: 'theme',
      label: 'Theme',
      type: 'select',
      options: [
        { value: 'auto', label: 'Auto (sección de al lado)' },
        { value: 'chapters', label: 'Chapters' },
        { value: 'nocturne', label: 'Nocturne' },
        { value: 'monolith', label: 'Monolith' },
        { value: 'velocity', label: 'Velocity' },
        { value: 'fizz', label: 'Fizz' },
        { value: 'atelier', label: 'Atelier' },
        { value: 'comic', label: 'Comic' },
        { value: 'unity', label: 'Unity' },
        { value: 'ratio', label: 'Ratio' },
        { value: 'vanta', label: 'Vanta' },
      ],
    },
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    { key: 'nameLabel', label: 'Name — label', type: 'text' },
    { key: 'emailLabel', label: 'Email — label', type: 'text' },
    { key: 'messageLabel', label: 'Message — label', type: 'text' },
    { key: 'submitLabel', label: 'Submit — label', type: 'text' },
    { key: 'sendingLabel', label: 'Sending — label', type: 'text' },
    { key: 'successMessage', label: 'Success message', type: 'textarea' },
    { key: 'errorMessage', label: 'Error message', type: 'textarea' },
    { key: 'note', label: 'Note', type: 'textarea' },
    {
      key: 'endpoint',
      label: 'Endpoint — https:// or /path (empty = demo)',
      type: 'text',
    },
  ],
  'commerce/ProductGrid': [
    {
      key: 'theme',
      label: 'Color',
      type: 'select',
      options: [
        { value: 'auto', label: 'Auto (sección de al lado)' },
        { value: 'chapters', label: 'Chapters · #ff4b00' },
        { value: 'nocturne', label: 'Nocturne · #d9ff3f' },
        { value: 'monolith', label: 'Monolith · #2b3cff' },
        { value: 'velocity', label: 'Velocity · #d9ff3f' },
        { value: 'fizz', label: 'Fizz · #ff3ea5' },
        { value: 'atelier', label: 'Atelier · #c8d0dc' },
        { value: 'comic', label: 'Comic · #e85a24' },
        { value: 'unity', label: 'Unity · #f4c518' },
        { value: 'ratio', label: 'Ratio · #e23c24' },
        { value: 'vanta', label: 'Vanta · #5b4cff' },
      ],
    },
    { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'body', label: 'Body', type: 'textarea' },
    // El checkout es una ruta (/checkout), no una sección seleccionable:
    // sus textos se editan desde acá y viajan como props `checkout*`.
    { key: 'checkoutEyebrow', label: 'Checkout · Eyebrow', type: 'text' },
    { key: 'checkoutTitle', label: 'Checkout · Title', type: 'text' },
    { key: 'checkoutBody', label: 'Checkout · Body', type: 'textarea' },
    {
      key: 'checkoutStepsText',
      label: 'Checkout · Pasos (uno por línea)',
      type: 'textarea',
    },
    { key: 'checkoutContactTitle', label: 'Checkout · Contacto', type: 'text' },
    { key: 'checkoutShippingTitle', label: 'Checkout · Envío', type: 'text' },
    {
      key: 'checkoutCountryOptionsText',
      label: 'Checkout · Países (uno por línea)',
      type: 'textarea',
    },
    { key: 'checkoutDeliveryTitle', label: 'Checkout · Entrega', type: 'text' },
    { key: 'checkoutStandardLabel', label: 'Checkout · Envío estándar', type: 'text' },
    { key: 'checkoutStandardNote', label: 'Checkout · Estándar — nota', type: 'text' },
    { key: 'checkoutExpressLabel', label: 'Checkout · Envío express', type: 'text' },
    { key: 'checkoutExpressNote', label: 'Checkout · Express — nota', type: 'text' },
    { key: 'checkoutPaymentTitle', label: 'Checkout · Pago', type: 'text' },
    { key: 'checkoutPayCardLabel', label: 'Checkout · Pago tarjeta', type: 'text' },
    { key: 'checkoutPayWalletLabel', label: 'Checkout · Pago billetera', type: 'text' },
    {
      key: 'checkoutPayTransferLabel',
      label: 'Checkout · Pago transferencia',
      type: 'text',
    },
    { key: 'checkoutSummaryTitle', label: 'Checkout · Resumen', type: 'text' },
    { key: 'checkoutPromoLabel', label: 'Checkout · Cupón — label', type: 'text' },
    { key: 'checkoutPromoCode', label: 'Checkout · Cupón válido', type: 'text' },
    { key: 'checkoutPromoOff', label: 'Checkout · Cupón — % off', type: 'text' },
    { key: 'checkoutShippingFlat', label: 'Checkout · Costo envío', type: 'text' },
    { key: 'checkoutExpressPrice', label: 'Checkout · Costo express', type: 'text' },
    {
      key: 'checkoutFreeShippingOver',
      label: 'Checkout · Envío gratis desde (0 = nunca)',
      type: 'text',
    },
    { key: 'checkoutPayLabel', label: 'Checkout · Botón pagar', type: 'text' },
    {
      key: 'checkoutTrustText',
      label: 'Checkout · Garantías (una por línea)',
      type: 'textarea',
    },
    { key: 'checkoutSuccessTitle', label: 'Checkout · Éxito — título', type: 'text' },
    { key: 'checkoutSuccessBody', label: 'Checkout · Éxito — texto', type: 'textarea' },
  ],
}

export function getSectionFields(sectionId) {
  return SECTION_FIELDS[sectionId] || []
}

/** Local preview uploads (blob:) / inline data — never ship in the ZIP. */
export function isEphemeralAssetUrl(value) {
  return typeof value === 'string' && /^(blob:|data:)/i.test(value)
}

export function sanitizeProps(sectionId, props) {
  if (!props || typeof props !== 'object') return undefined
  const fields = getSectionFields(sectionId)
  if (fields.length === 0) return undefined
  const byKey = new Map(fields.map((f) => [f.key, f]))
  const cleaned = {}
  for (const [key, value] of Object.entries(props)) {
    const field = byKey.get(key)
    if (!field || typeof value !== 'string') continue
    const trimmed = value.slice(0, 2000)
    if (!trimmed) continue
    if (field.type === 'select') {
      const ok = (field.options || []).some((o) => o.value === trimmed)
      if (!ok) continue
    }
    // Preview: allow blob:/data:. Checkout strips them via compositionToRecipe.
    if (
      (field.type === 'model' || field.type === 'image') &&
      !isEphemeralAssetUrl(trimmed) &&
      !/^(https:\/\/|\/)\S/i.test(trimmed)
    ) {
      continue
    }
    cleaned[key] = trimmed
  }
  return Object.keys(cleaned).length ? cleaned : undefined
}
