/**
 * Modelos de la home (orden de lista: la página los ordena por precio). La
 * lista de SKUs la verifica `npm run check` contra el catálogo y las rutas.
 */
export const TEMPLATE_META = [
  {
    id: '01',
    sku: 'chapters',
    name: 'CHAPTERS',
    path: '/templates/chapters',
    category: 'EDITORIAL',
    tagline: 'kinetic stories',
    palette: ['#f2efe9', '#161412', '#ff4b00'],
  },
  {
    id: '02',
    sku: 'nocturne',
    name: 'NOCTURNE',
    path: '/templates/nocturne',
    category: 'CINEMA',
    tagline: 'AFTER DARK',
    palette: ['#0e0e11', '#ece9e2', '#d9ff3f'],
  },
  {
    id: '03',
    sku: 'monolith',
    name: 'MONOLITH',
    path: '/templates/monolith',
    category: 'SYSTEM',
    tagline: 'brutal form',
    palette: ['#cdcbc4', '#101010', '#2b3cff'],
  },
  {
    id: '04',
    sku: 'velocity',
    name: 'VELOCITY',
    path: '/templates/velocity',
    category: 'ATHLETE',
    tagline: 'full send',
    palette: ['#0a1a12', '#ece9e2', '#d9ff3f'],
  },
  {
    id: '05',
    sku: 'fizz',
    name: 'FIZZ',
    path: '/templates/fizz',
    category: 'POP',
    tagline: 'drink the spark',
    palette: ['#241352', '#fff3e2', '#ff3ea5'],
  },
  {
    id: '06',
    sku: 'atelier',
    name: 'ATELIER',
    path: '/templates/atelier',
    category: 'STUDIO',
    tagline: 'scroll the fog',
    palette: ['#0b0c10', '#f2f2f2', '#c8d0dc'],
  },
  {
    id: '07',
    sku: 'comic',
    name: 'COMIC',
    path: '/templates/comic',
    category: 'SCRAPBOOK',
    tagline: 'torn panels',
    palette: ['#d8d4cc', '#2a2622', '#e85a24'],
  },
  {
    id: '08',
    sku: 'unity',
    name: 'UNITY',
    path: '/templates/unity',
    category: 'EDITORIAL',
    tagline: 'shared field',
    palette: ['#e7e4dc', '#0a0a0a', '#2c4a42'],
  },
  {
    id: '09',
    sku: 'atrium',
    name: 'ATRIUM',
    path: '/templates/atrium',
    category: 'ARCHITECTURE',
    tagline: 'mass and measure',
    palette: ['#f4f1ea', '#111111', '#111111'],
  },
  {
    id: '10',
    sku: 'meridian',
    name: 'MERIDIAN',
    path: '/templates/meridian',
    category: 'REAL ESTATE',
    tagline: 'scroll the site',
    palette: ['#dfd8cf', '#2a2622', '#8f7a5e'],
  },
]
