/**
 * Allowlist server-side de props editables por sección.
 * Debe coincidir con src/lib/sectionFields.js.
 */
export const ALLOWED_PROPS_BY_SECTION = Object.freeze({
  'chapters/NavMinimal': ['brand', 'linksText'],
  'chapters/HeroKinetic': [
    'lineOne',
    'lineTwo',
    'lineThree',
    'kicker',
    'meta',
    'hint',
  ],
  'chapters/ManifestoReveal': ['chapter', 'total', 'label'],
  'chapters/QuoteBreak': [
    'chapter',
    'total',
    'label',
    'quote',
    'attribution',
  ],
  'chapters/FooterCTA': ['ctaWord', 'email', 'legal'],
  'nocturne/NavNocturne': ['brand', 'marker', 'linksText'],
  'nocturne/HeroCinematic': [
    'titleTop',
    'titleBottom',
    'kicker',
    'meta',
    'hint',
  ],
  'nocturne/OutroCTA': ['ctaWord', 'email', 'legal'],
  'monolith/NavBrutal': ['brand', 'linksText'],
  'monolith/HeroThree': ['title', 'subtitle', 'meta', 'hint', 'shape', 'modelUrl'],
  'monolith/FooterBrutal': ['ctaWord', 'email', 'legal'],
  'fizz/NavFizz': [
    'brand',
    'shopLabel',
    'shopItems',
    'learnLabel',
    'learnItems',
    'linkLabel',
    'cta',
  ],
  'fizz/HeroBubbles': [
    'title',
    'tagline',
    'meta',
    'hint',
    'flavor',
    'canImage',
    'canLabel',
    'modelUrl',
  ],
  'fizz/FlavorWorlds': ['eyebrow'],
  'fizz/BubbleBenefits': ['eyebrow', 'title'],
  'fizz/CanCarousel': [
    'eyebrow',
    'title',
    'cta',
    'canLabel',
    'can1Name',
    'can1Note',
    'can1Image',
    'can2Name',
    'can2Note',
    'can2Image',
    'can3Name',
    'can3Note',
    'can3Image',
    'can4Name',
    'can4Note',
    'can4Image',
    'can5Name',
    'can5Note',
    'can5Image',
  ],
  'fizz/PopManifesto': ['eyebrow', 'text'],
  'fizz/FooterSplash': ['ctaWord', 'email', 'legal'],
  'velocity/NavVelocity': ['brand', 'cta', 'linksText'],
  'velocity/HeroStrike': [
    'lineLeft',
    'lineLeft2',
    'lineRight',
    'lineRight2',
    'caption',
    'imgBack',
    'imgMid',
    'imgFront',
  ],
  'velocity/HelmetGrid': ['eyebrow', 'title', 'body'],
  'velocity/TrackMerge': [
    'pathLabelA',
    'pathLabelB',
    'mergeTitleA',
    'mergeTitleB',
    'mergeAccent',
  ],
  'velocity/ParallaxRise': ['eyebrow', 'title', 'body', 'cta'],
  'velocity/FooterVelocity': ['line', 'legal'],
  'atelier/NavAtelier': ['brand', 'cta', 'label', 'menuLabel', 'linksText'],
  'atelier/HeroMeaning': ['line1', 'line2', 'meta', 'hint'],
  'atelier/AboutClarity': ['eyebrow', 'title', 'body'],
  'atelier/ServicesStone': [
    'eyebrow',
    'title',
    'service1Title',
    'service1Body',
    'service2Title',
    'service2Body',
    'service3Title',
    'service3Body',
    'service4Title',
    'service4Body',
  ],
  'atelier/VisionShutter': ['line1', 'line2', 'word1', 'word2', 'word3'],
  'atelier/SelectedWork': ['title', 'cta'],
  'atelier/KeyFacts': ['eyebrow', 'title'],
  'atelier/WordStripe': ['line1', 'line2', 'word1', 'word2', 'word3'],
  'atelier/StudioCards': ['note', 'cta'],
  'atelier/FooterAtelier': [
    'eyebrow',
    'line',
    'cta',
    'brand',
    'legal',
    'email',
    'phone',
    'hint',
  ],
  'unity/NavUnity': ['brand', 'logo', 'logoSrc', 'linksText', 'menuLabel'],
  'unity/HeroTwin': ['body', 'headline'],
  'unity/MosaicSlider': [
    'eyebrow',
    'title',
    'img1',
    'img2',
    'img3',
    'img4',
    'img5',
    'img6',
    'img7',
    'img8',
  ],
  'unity/UniversalLang': ['eyebrow', 'title', 'body', 'number', 'numberLabel'],
  'unity/LanguageBlock': [
    'eyebrow',
    'line1',
    'line2',
    'line3',
    'note',
    'bg',
    'fg',
    'img1',
    'img2',
    'img3',
    'anchor',
  ],
  'unity/LastPortrait': [
    'title',
    'name',
    'body',
    'question',
    'caption',
    'img',
    'stat1Label',
    'stat1Value',
    'stat2Label',
    'stat2Value',
    'stat3Label',
    'stat3Value',
  ],
  'unity/StageLines': [
    'eyebrow1',
    'line1',
    'img1',
    'eyebrow2',
    'line2',
    'img2',
  ],
  'unity/FooterTrophy': [
    'eyebrow',
    'title',
    'accentWord',
    'metaLeft',
    'metaRight',
    'orbSrc',
  ],
  'ratio/NavRatio': [
    'brand',
    'linksText',
    'ruptureLabel',
    'onLabel',
    'offLabel',
    'credit',
    'menuLabel',
  ],
  'ratio/HeroTools': [
    'word1',
    'word2',
    'word3',
    'word4',
    'word5',
    'note',
    'aside',
  ],
  'ratio/FourPlates': [
    'eyebrow',
    'plate1Title',
    'plate2Title',
    'plate3Title',
    'plate4Title',
  ],
  'ratio/SplitStudy': [
    'kicker',
    'meta',
    'index',
    'specLabel',
    'specValue',
    'spec2Label',
    'spec2Value',
    'spec3Label',
    'spec3Value',
    'spec4Label',
    'spec4Value',
    'quote',
    'quoteBy',
    'quoteRole',
    'panel2Label',
    'panel2Size',
    'img',
    'img2',
    'anchor',
  ],
  'ratio/FitStack': [
    'noteLabel',
    'note1',
    'note2',
    'note2Mark',
    'note3',
    'note3Mark',
    'phrase',
    'breakLine',
    'rulesLine',
    'worthLine',
    'closer',
    'brand',
    'studio',
    'anchor',
  ],
  'ratio/PlateStudy': [
    'index',
    'title',
    'variant',
    'specLabel',
    'specValue',
    'spec2Label',
    'spec2Value',
    'spec3Label',
    'spec3Value',
    'spec4Label',
    'spec4Value',
    'caseTitle',
    'caseMeta',
    'img',
    'img2',
    'step1Label',
    'step1Body',
    'step2Label',
    'step2Body',
    'notes',
    'anchor',
  ],
  'ratio/BreakRules': ['line1', 'line2', 'line3', 'aside', 'anchor'],
  'ratio/FooterLedger': [
    'title',
    'ghost',
    'hint',
    'brand',
    'studio',
    'row1Label',
    'row1Value',
    'row2Label',
    'row2Value',
    'row3Label',
    'row3Value',
    'row4Label',
    'row4Value',
    'spine1Title',
    'spine1Author',
    'spine2Title',
    'spine2Author',
    'spine3Title',
    'spine3Author',
    'spine4Title',
    'spine4Author',
    'spine5Title',
    'spine5Author',
  ],
  'vanta/NavVanta': [
    'brand',
    'linksText',
    'playLabel',
    'liveLabel',
    'menuLabel',
    'discoverLabel',
    'drawerLinksText',
    'connectLabel',
    'socialText',
    'buyLabel',
    'buyMarket',
    'closeLabel',
    'langLabel',
    'pageLabel',
    'year',
  ],
  'vanta/BootVanta': ['brand', 'loadingLabel', 'soundLabel', 'readyLabel', 'playLabel'],
  'vanta/HeroOperators': [
    'line',
    'word1',
    'word2',
    'word3',
    'tag1',
    'tag2',
    'tag3',
    'worldLine',
    'hint',
    'img',
    'img2',
  ],
  'vanta/KeeperVista': ['worldLine', 'line', 'power', 'index', 'img', 'img2', 'img3', 'img4'],
  'vanta/CollectionDesk': [
    'kicker',
    'mark',
    'title',
    'crystalLabel',
    'eyeLabel',
    'img',
    'img2',
    'img3',
  ],
  'vanta/OperatorFan': [
    'kicker',
    'title',
    'body',
    'img',
    'img2',
    'img3',
    'img4',
    'img5',
    'img6',
    'img7',
    'img8',
  ],
  'vanta/CitadelStage': ['index', 'title', 'body', 'holdHint', 'feedLabel', 'img', 'img2'],
  'vanta/FactionHold': [
    'index',
    'kicker',
    'line',
    'leftName',
    'leftBody',
    'rightName',
    'rightBody',
    'holdHint',
    'feedLabel',
    'img',
    'img2',
  ],
  'vanta/WorldVista': ['index', 'title', 'body', 'img', 'img2', 'img3', 'img4'],
  'vanta/FooterDrop': [
    'mark',
    'hint',
    'cta',
    'boot',
    'fileLine',
    'story',
    'journal',
    'media',
    'gallery',
    'about',
    'contact',
    'legal',
    'col1',
    'col2',
    'col3',
    'img',
    'img2',
    'img3',
    'img4',
  ],
  'contact/ContactForm': [
    'theme',
    'eyebrow',
    'title',
    'body',
    'nameLabel',
    'emailLabel',
    'messageLabel',
    'submitLabel',
    'sendingLabel',
    'successMessage',
    'errorMessage',
    'note',
    'endpoint',
  ],
  // Los `checkout*` no los usa la grilla: viajan a la ruta /checkout
  // (src/lib/shop/checkoutProps.js) y por eso se validan acá igual.
  'commerce/ProductGrid': [
    'theme',
    'eyebrow',
    'title',
    'body',
    'checkoutEyebrow',
    'checkoutTitle',
    'checkoutBody',
    'checkoutStepsText',
    'checkoutContactTitle',
    'checkoutShippingTitle',
    'checkoutCountryOptionsText',
    'checkoutDeliveryTitle',
    'checkoutStandardLabel',
    'checkoutStandardNote',
    'checkoutExpressLabel',
    'checkoutExpressNote',
    'checkoutPaymentTitle',
    'checkoutPayCardLabel',
    'checkoutPayWalletLabel',
    'checkoutPayTransferLabel',
    'checkoutSummaryTitle',
    'checkoutPromoLabel',
    'checkoutPromoCode',
    'checkoutPromoOff',
    'checkoutShippingFlat',
    'checkoutExpressPrice',
    'checkoutFreeShippingOver',
    'checkoutPayLabel',
    'checkoutTrustText',
    'checkoutSuccessTitle',
    'checkoutSuccessBody',
  ],
})

const SHAPE_PRESETS = new Set([
  'icosahedron',
  'box',
  'octahedron',
  'torus',
  'sphere',
])

const FLAVOR_PRESETS = new Set(['berry', 'citrus', 'tropical', 'mint'])

const THEME_PRESETS = new Set([
  'auto',
  'chapters',
  'nocturne',
  'monolith',
  'velocity',
  'fizz',
  'atelier',
  'comic',
  'unity',
  'ratio',
  'vanta',
])

/**
 * Asset URLs baked into the sold ZIP must be a real path/URL:
 * https:// or a site-relative path like /my-can.png.
 * blob:/data: (builder-preview uploads) never survive the session.
 */
const ASSET_URL_RE = /^(https:\/\/|\/)\S{1,500}$/i

const ASSET_URL_KEYS = new Set([
  'modelUrl',
  'can1Image',
  'can2Image',
  'can3Image',
  'can4Image',
  'can5Image',
  'img',
  'img1',
  'img2',
  'img3',
  'img4',
  'img5',
  'img6',
  'img7',
  'img8',
  'logoSrc',
  'orbSrc',
])

export function sanitizeSectionProps(sectionId, props) {
  if (!props || typeof props !== 'object' || Array.isArray(props)) return undefined
  const allowed = ALLOWED_PROPS_BY_SECTION[sectionId]
  if (!allowed) return undefined
  const allow = new Set(allowed)
  const cleaned = {}
  for (const [key, value] of Object.entries(props)) {
    if (!allow.has(key)) continue
    if (typeof value !== 'string') continue
    const trimmed = value.slice(0, 2000)
    if (!trimmed) continue
    if (key === 'shape' && !SHAPE_PRESETS.has(trimmed)) continue
    if (key === 'flavor' && !FLAVOR_PRESETS.has(trimmed)) continue
    if (key === 'theme' && !THEME_PRESETS.has(trimmed)) continue
    if (ASSET_URL_KEYS.has(key) && !ASSET_URL_RE.test(trimmed)) continue
    if (key === 'endpoint' && !ASSET_URL_RE.test(trimmed)) continue
    cleaned[key] = trimmed
  }
  return Object.keys(cleaned).length ? cleaned : undefined
}
